### ISSUE TITLE
Ability to pass includes and excludes

### ISSUE THREAD

**Issue by mricon** [jordanconway/puppet-rdiff_backup#4]
Need to be able to pass includes and excludes in the hiera config, like so:

``` yaml
rdiff_backup::rdiff_exports:
  var:
    path: '/var'
    cron_hour: '*/6'
    includes:
      - '/var/log/httpd'
      - '/var/log/fastcgi'
    excludes:
      - '/var/log/httpd/*error*'
```

Which would generate something like the following, with includes preceding excludes.

`rdiff-backup --include '/var/log/httpd' --include '/var/log/fastcgi' --exclude '/var/log/httpd/*error*' /var [remote-server]`
